spring:
  application:
    name: "Spring Boot 24497"
---
spring:
  config:
    activate:
      on-profile: test
---
spring:
  config:
    activate:
      on-profile: dev
    import: file:./config/additional.yaml